package com.nano_tablet.nanotabletrfid.mainApp.domain.schemas

import com.nano_tablet.nanotabletrfid.mainApp.domain.schemas.CommonSchemas.CeProjectpricelist
import com.nano_tablet.nanotabletrfid.mainApp.domain.schemas.CommonSchemas.Createdby
import com.nano_tablet.nanotabletrfid.mainApp.domain.schemas.CommonSchemas.Createdonbehalfby
import com.nano_tablet.nanotabletrfid.mainApp.domain.schemas.CommonSchemas.Modifiedby
import com.nano_tablet.nanotabletrfid.mainApp.domain.schemas.CommonSchemas.NewHlavniResitel
import com.nano_tablet.nanotabletrfid.mainApp.domain.schemas.CommonSchemas.NewKontaktniosoba
import com.nano_tablet.nanotabletrfid.mainApp.domain.schemas.CommonSchemas.NewTypProjektu
import com.nano_tablet.nanotabletrfid.mainApp.domain.schemas.CommonSchemas.Ownerid
import com.nano_tablet.nanotabletrfid.mainApp.domain.schemas.CommonSchemas.Owningbusinessunit
import com.nano_tablet.nanotabletrfid.mainApp.domain.schemas.CommonSchemas.Owninguser
import com.nano_tablet.nanotabletrfid.mainApp.domain.schemas.CommonSchemas.PsaCustomerid
import com.nano_tablet.nanotabletrfid.mainApp.domain.schemas.CommonSchemas.Transactioncurrencyid

data class ProjectSchema(
    val ce_analyza: Boolean,
    val ce_ctdataaprohlizec: Boolean,
    val ce_financebalance: Double,
    val ce_financebalance_base: Double,
    val ce_obrazkyvidea: Boolean,
    val ce_odpocetdph: Int,
    val ce_pedanivysledku: Int,
    val ce_projectpricelist: CeProjectpricelist,
    val ce_stlmodel: Boolean,
    val ce_sumquotes: Double,
    val ce_sumquotes_date: String,
    val ce_sumquotes_state: Int,
    val ce_sumreservation: Double,
    val ce_sumreservation_base: Double,
    val ce_sumreservation_date: String,
    val ce_sumreservation_state: Int,
    val ce_vystupnizprava: Boolean,
    val createdby: Createdby,
    val createdon: String,
    val createdonbehalfby: Createdonbehalfby,
    val dyn_imported_vut: Boolean,
    val entityname: String,
    val exchangerate: Double,
    val ge_input_to_evaluation: Boolean,
    val ge_input_to_mi: Boolean,
    val ge_name_eng: String,
    val ge_poznamka: String,
    val ge_publish_in_profile: Boolean,
    val ge_support_cms: Boolean,
    val ge_udrzitelnost: Boolean,
    val id: String,
    val modifiedby: Modifiedby,
    val modifiedon: String,
    val new_aktualizacerezervaci: Boolean,
    val new_archiv: Boolean,
    val new_cn_poslana: Boolean,
    val new_czbi: Boolean,
    val new_czbi_prihlaska: Boolean,
    val new_dofinancovanivut: Boolean,
    val new_dofinancovnzneveejnchzdroj: Boolean,
    val new_doruceno: Boolean,
    val new_eubi: Boolean,
    val new_flatrate: Boolean,
    val new_fullcost: Boolean,
    val new_fuup: Boolean,
    val new_hlavni_resitel: NewHlavniResitel,
    val new_investice: Boolean,
    val new_investigator_national_abroad: Boolean,
    val new_kontaktniosoba: NewKontaktniosoba,
    val new_kratkynazev: String,
    val new_mafil_return_flow: Boolean,
    val new_mafil_zpracovani_dat: Boolean,
    val new_mirkasmazat_state: Int,
    val new_mistomereni: Int,
    val new_mu_projekt_zrusen: Boolean,
    val new_mu_zakazkaveur: Boolean,
    val new_mubic: Boolean,
    val new_mubioit: Boolean,
    val new_mucellim: Boolean,
    val new_mucryoem: Boolean,
    val new_mugenomics: Boolean,
    val new_mumafil: Boolean,
    val new_munanobio: Boolean,
    val new_munmr: Boolean,
    val new_muplants: Boolean,
    val new_muproteomics: Boolean,
    val new_muxray: Boolean,
    val new_nabdka: Boolean,
    val new_new_notifikace2terminvyporadani: Boolean,
    val new_notifikace1terminvyporadani: Boolean,
    val new_notifikaceposledniterminprozadostozmenu: Boolean,
    val new_notifikaceterminmonitorovacizpravy: Boolean,
    val new_odpoetdph: Boolean,
    val new_orgtype: Int,
    val new_pedfinancovn: Boolean,
    val new_pristup_eubi: Boolean,
    val new_projekt_kontrola: Boolean,
    val new_projektvut: Boolean,
    val new_rezervace_hodiny_soucet: Double,
    val new_rezervace_hodiny_soucet_date: String,
    val new_rezervace_hodiny_soucet_state: Int,
    val new_riat: Boolean,
    val new_samostatnbankovnet: Boolean,
    val new_shpimport: Boolean,
    val new_soucet_hodin_rezervace: Double,
    val new_soucet_hodin_rezervace_date: String,
    val new_soucet_hodin_rezervace_state: Int,
    val new_soucet_nabidka_hodiny_state: Int,
    val new_spolueitel: Boolean,
    val new_stavprojektu: Int,
    val new_strukturovanrozpoeterpn: Boolean,
    val new_typ_projektu: NewTypProjektu,
    val new_umisteni_dokumentu: Boolean,
    val new_vstupnizprava: Int,
    val new_vystupy_predany: Boolean,
    val new_vzorky_odeslany: Boolean,
    val new_wp1: Boolean,
    val new_wp10: Boolean,
    val new_wp11: Boolean,
    val new_wp2: Boolean,
    val new_wp3: Boolean,
    val new_wp4: Boolean,
    val new_wp5: Boolean,
    val new_wp6: Boolean,
    val new_wp7: Boolean,
    val new_wp8: Boolean,
    val new_wp9: Boolean,
    val new_z_primych_nakladu: Boolean,
    val new_zalozitprveksppvsapu: Boolean,
    val new_zkontrolovat: Boolean,
    val new_zosobnichnakladu: Boolean,
    val new_zprava_poslana: Boolean,
    val ownerid: Ownerid,
    val owningbusinessunit: Owningbusinessunit,
    val owninguser: Owninguser,
    val processid: String,
    val psa_customerid: PsaCustomerid,
    val psa_invoiceable: Boolean,
    val psa_name: String,
    val psa_projectsid: String,
    val psa_type: Int,
    val stageid: String,
    val statecode: Int,
    val statuscode: Int,
    val transactioncurrencyid: Transactioncurrencyid,
    val traversedpath: String
)

